# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e59df39da32ad93f0516f47c911ce58f4174a4c57015d496ed8eb3a24d782bf445fecb2029f9e907b1bb55df4724cab58a6631d13b2142e6bf99b89fdf43dd5f

test:
  secret_key_base: 12768357c352a2d34bed15a748aec70bc486ada7d88f39dd81962709e487f3b751c4b478c36a598bc3f521fcc74ea7f110368d616d539f11497511f8fc3b0c6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
